name: Keep App Awake
on:
  schedule:
    - cron: '0 */10 * * *'
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Keepalive Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Keepalive ping"
          git push
